### ISSUE TITLE
Problem running the project

### ISSUE THREAD

**Issue by pol-todo** [CrispenGari/machine-translator#1]
Hi Crispen,

I'm getting an error about a missing JSON file for vocab (`machine-translator/translation/models/eng-deu/static/src_vocab.json`). Any chance you can see what I'm doing wrong? Am I missing a file?

Here's what I have:

```
 ~/Doc/p/machine-translator  on main ?1  python main.py                                                                       ✔  machine-translator   2.6.3   at 16:14:49 
 ✅ LOADING TOKENIZERS

 ✅ LOADING TOKENIZERS DONE!

 ✅ LOADING TRANSLATION MODELS

Traceback (most recent call last):
  File "/Users/manolo/Documents/python/machine-translator/main.py", line 22, in <module>
    from resolvers.mutations import mutation
  File "/Users/manolo/Documents/python/machine-translator/resolvers/mutations/__init__.py", line 2, in <module>
    from translation import getFunctionParams, translate_sentence, EOS_TOKEN, UNK_TOKEN, device, meta
  File "/Users/manolo/Documents/python/machine-translator/translation/__init__.py", line 88, in <module>
    DE_DE_DICT, DE_EN_DICT = createDictMappings('eng-deu')
  File "/Users/manolo/Documents/python/machine-translator/translation/__init__.py", line 59, in createDictMappings
    with open(src_json_path, 'r') as src, open(trg_json_path, 'r') as trg:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/manolo/Documents/python/machine-translator/translation/models/eng-deu/static/src_vocab.json'


```

**Comment by CrispenGari** [comment]
Yes you are missing a lot of things to run this API, consider reading the README file but I know what you are missing exactly. The error is clear, you need to have a lot of files that you are missing. In order to get these files  you need to run the several notebooks to train and save models and static files that are missing.

### Language Identification
This is the notebook for [language identification model](https://github.com/CrispenGari/nlp-pytorch/blob/main/06_Language_Identification/02_Language_Identification_Saving_Donloading.ipynb)

### Machine Translation Models
Notebooks for bidirectional machine translation for the listed languages are found [here](https://github.com/CrispenGari/nlp-pytorch/tree/main/07_NMT_Project)


> If you face any problem after having all the files let me know.

**Comment by pol-todo** [comment]
Very cool, I'll check out those notebooks to train up the models. Thanks a ton for the help. I'm new to Python so I'll probably have a few more questions.

**Comment by pol-todo** [comment]
Also, one suggestion, if you put that part about the notebooks in the beginning of your README.md, I think more people would be able to evaluate your project. (It'd be clearer the steps needed to setup).

**Comment by CrispenGari** [comment]
Yes i will do that, you should also read the Notebooks they are step by step guidelines for data preparation before training. If you have any question feel free to ask

**Comment by pol-todo** [comment]
Awesome! I saw that yesterday, signed up for Google Colab last night, and should be working through those notebooks later this weekend.

**Comment by CrispenGari** [comment]
Yes do that, also you need to start by checking the data preparation Notebook where you will find instructions on how to get the dataset and prepare it
